// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwp5pBoqJvikPjb_71ThthTQTN1GwcbEQ',
    appId: '1:850024065962:web:6753d67e26517341cb19d3',
    messagingSenderId: '850024065962',
    projectId: 'medx-ab74f',
    authDomain: 'medx-ab74f.firebaseapp.com',
    storageBucket: 'medx-ab74f.firebasestorage.app',
    measurementId: 'G-PVRZRBS64B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANm0twdhXdgUqcGgL_PHDQ952gn-_I3sw',
    appId: '1:850024065962:android:e7901a1f9254e99acb19d3',
    messagingSenderId: '850024065962',
    projectId: 'medx-ab74f',
    storageBucket: 'medx-ab74f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACN6P1qZeM82MCr6fXjjpWHP_MKTTxbvg',
    appId: '1:850024065962:ios:803d353650622183cb19d3',
    messagingSenderId: '850024065962',
    projectId: 'medx-ab74f',
    storageBucket: 'medx-ab74f.firebasestorage.app',
    iosBundleId: 'com.example.project1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACN6P1qZeM82MCr6fXjjpWHP_MKTTxbvg',
    appId: '1:850024065962:ios:803d353650622183cb19d3',
    messagingSenderId: '850024065962',
    projectId: 'medx-ab74f',
    storageBucket: 'medx-ab74f.firebasestorage.app',
    iosBundleId: 'com.example.project1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwp5pBoqJvikPjb_71ThthTQTN1GwcbEQ',
    appId: '1:850024065962:web:9d7b041e8e30698bcb19d3',
    messagingSenderId: '850024065962',
    projectId: 'medx-ab74f',
    authDomain: 'medx-ab74f.firebaseapp.com',
    storageBucket: 'medx-ab74f.firebasestorage.app',
    measurementId: 'G-EWT3Q400Y0',
  );
}
